In [25]:
import pandas as pd
import os

In [27]:
folder_path = r"C:\Users\kband\Documents\ACS2020-2021"
os.listdir(folder_path)

['.ipynb_checkpoints',
 'ACSDT1Y2021.B15003-Data.csv',
 'ACSDT1Y2022.B15003-Data.csv',
 'ACSDT1Y2023.B15003-Data.csv',
 'ACSDT1Y2024.B03002-Data.csv',
 'ACSDT1Y2024.B15003-Data.csv',
 'ACSDT5Y2020.B03002-Data.csv',
 'ACSDT5Y2020.B15003-Data.csv',
 'ACSDT5Y2020.B19001-Data.csv',
 'ACSDT5Y2021.B03002-Data.csv',
 'ACSDT5Y2021.B19001-Data.csv',
 'ACSDT5Y2022.B03002-Data.csv',
 'ACSDT5Y2022.B19001-Data.csv',
 'ACSDT5Y2023.B03002-Data.csv',
 'ACSDT5Y2023.B19001-Data.csv',
 'ACSDT5Y2024.B19001-Data.csv',
 'ACSDT5YSPT2021.B19001-Data.csv']

In [29]:
file_2020 = r"C:\Users\kband\Documents\ACS2020-2021/ACSDT5Y2020.B03002-Data.csv"
df_race = pd.read_csv(file_2020)
df_race.head()

,GEO_ID,NAME,B03002_001E,B03002_001M,B03002_002E,B03002_002M,B03002_003E,B03002_003M,B03002_004E,B03002_004M,...,B03002_017M,B03002_018E,B03002_018M,B03002_019E,B03002_019M,B03002_020E,B03002_020M,B03002_021E,B03002_021M,Unnamed: 44
0,Geography,Geographic Area Name,Estimate!!Total:,Margin of Error!!Total:,Estimate!!Total:!!Not Hispanic or Latino:,Margin of Error!!Total:!!Not Hispanic or Latino:,Estimate!!Total:!!Not Hispanic or Latino:!!Whi...,Margin of Error!!Total:!!Not Hispanic or Latin...,Estimate!!Total:!!Not Hispanic or Latino:!!Bla...,Margin of Error!!Total:!!Not Hispanic or Latin...,...,Margin of Error!!Total:!!Hispanic or Latino:!!...,Estimate!!Total:!!Hispanic or Latino:!!Some ot...,Margin of Error!!Total:!!Hispanic or Latino:!!...,Estimate!!Total:!!Hispanic or Latino:!!Two or ...,Margin of Error!!Total:!!Hispanic or Latino:!!...,Estimate!!Total:!!Hispanic or Latino:!!Two or ...,Margin of Error!!Total:!!Hispanic or Latino:!!...,Estimate!!Total:!!Hispanic or Latino:!!Two or ...,Margin of Error!!Total:!!Hispanic or Latino:!!...,NaN
1,0500000US01001,"Autauga County, Alabama",55639,*****,54038,*****,41160,78,10849,345,...,37,273,242,297,159,292,160,5,12,NaN
2,0500000US01003,"Baldwin County, Alabama",218289,*****,208342,*****,180955,654,19027,744,...,29,2658,709,1427,493,1220,431,207,203,NaN
3,0500000US01005,"Barbour County, Alabama",25026,*****,23916,*****,11332,83,11889,179,...,23,620,183,188,79,188,79,0,23,NaN
4,0500000US01007,"Bibb County, Alabama",22374,*****,21774,*****,16650,23,4971,111,...,23,9,19,29,42,0,23,29,42,NaN

In [31]:
df_race = df_race[df_race["NAME"] != "Geographic Area Name"]

In [33]:
df_race = df_race.reset_index(drop=True)

In [35]:
df_race.columns.tolist()

['GEO_ID',
 'NAME',
 'B03002_001E',
 'B03002_001M',
 'B03002_002E',
 'B03002_002M',
 'B03002_003E',
 'B03002_003M',
 'B03002_004E',
 'B03002_004M',
 'B03002_005E',
 'B03002_005M',
 'B03002_006E',
 'B03002_006M',
 'B03002_007E',
 'B03002_007M',
 'B03002_008E',
 'B03002_008M',
 'B03002_009E',
 'B03002_009M',
 'B03002_010E',
 'B03002_010M',
 'B03002_011E',
 'B03002_011M',
 'B03002_012E',
 'B03002_012M',
 'B03002_013E',
 'B03002_013M',
 'B03002_014E',
 'B03002_014M',
 'B03002_015E',
 'B03002_015M',
 'B03002_016E',
 'B03002_016M',
 'B03002_017E',
 'B03002_017M',
 'B03002_018E',
 'B03002_018M',
 'B03002_019E',
 'B03002_019M',
 'B03002_020E',
 'B03002_020M',
 'B03002_021E',
 'B03002_021M',
 'Unnamed: 44']

In [37]:
df_race = df_race[
    [
        "GEO_ID",
        "NAME",
        "B03002_001E",  # total population
        "B03002_003E",  # NH-White
        "B03002_004E",  # NH-Black
        "B03002_005E",  # AIAN
        "B03002_006E",  # Asian
        "B03002_007E",  # NHOPI
        "B03002_008E",  # Other
        "B03002_009E",  # Multiracial
        "B03002_012E"   # Hispanic
    ]
]

In [39]:
df_race = df_race.rename(columns={
    "B03002_001E": "Total",
    "B03002_003E": "NH_White",
    "B03002_004E": "NH_Black",
    "B03002_005E": "AIAN",
    "B03002_006E": "Asian",
    "B03002_007E": "NHOPI",
    "B03002_008E": "Other",
    "B03002_009E": "Multiracial",
    "B03002_012E": "Hispanic"
})

In [41]:
df_race.head()

,GEO_ID,NAME,Total,NH_White,NH_Black,AIAN,Asian,NHOPI,Other,Multiracial,Hispanic
0,0500000US01001,"Autauga County, Alabama",55639,41160,10849,155,649,0,101,1124,1601
1,0500000US01003,"Baldwin County, Alabama",218289,180955,19027,1327,2033,10,740,4250,9947
2,0500000US01005,"Barbour County, Alabama",25026,11332,11889,81,122,1,157,334,1110
3,0500000US01007,"Bibb County, Alabama",22374,16650,4971,12,56,0,0,85,600
4,0500000US01009,"Blount County, Alabama",57755,50065,771,49,236,55,179,1038,5362

In [43]:
race_cols = ["NH_White", "NH_Black", "AIAN", "Asian", "NHOPI", "Other", "Multiracial", "Hispanic", "Total"]

for col in race_cols:
    df_race[col] = pd.to_numeric(df_race[col], errors="coerce")

In [45]:
df_race["race_sum"] = (
    df_race["NH_White"] +
    df_race["NH_Black"] +
    df_race["AIAN"] +
    df_race["Asian"] +
    df_race["NHOPI"] +
    df_race["Other"] +
    df_race["Multiracial"] +
    df_race["Hispanic"]
)

In [47]:
df_race[["NAME", "Total", "race_sum"]].head()

                      NAME   Total  race_sum
0  Autauga County, Alabama   55639     55639
1  Baldwin County, Alabama  218289    218289
2  Barbour County, Alabama   25026     25026
3     Bibb County, Alabama   22374     22374
4   Blount County, Alabama   57755     57755

In [49]:
import pandas as pd
import re

df_edu = pd.read_csv(r"C:\Users\kband\Documents\ACS2020-2021\ACSDT5Y2020.B15003-Data.csv", skiprows=1)

# rename ID columns
df_edu = df_edu.rename(columns={
    "Geography": "GEO_ID",
    "Geographic Area Name": "NAME"
})

# keep only estimate columns, drop margin-of-error columns
estimate_cols = ["GEO_ID", "NAME"] + [c for c in df_edu.columns if c.startswith("Estimate!!")]

df_edu = df_edu[estimate_cols].copy()

# clean the estimate column names
def clean_col(c):
    c = c.replace("Estimate!!Total!!", "")
    c = c.replace("Estimate!!", "")
    c = c.replace("Total!!", "")
    c = c.replace("!!", " ")
    c = c.replace(":", "")
    return c.strip()

df_edu.columns = [clean_col(c) if c not in ["GEO_ID", "NAME"] else c for c in df_edu.columns]

df_edu.columns.tolist()

['GEO_ID',
 'NAME',
 'Total',
 'Total No schooling completed',
 'Total Nursery school',
 'Total Kindergarten',
 'Total 1st grade',
 'Total 2nd grade',
 'Total 3rd grade',
 'Total 4th grade',
 'Total 5th grade',
 'Total 6th grade',
 'Total 7th grade',
 'Total 8th grade',
 'Total 9th grade',
 'Total 10th grade',
 'Total 11th grade',
 'Total 12th grade, no diploma',
 'Total Regular high school diploma',
 'Total GED or alternative credential',
 'Total Some college, less than 1 year',
 'Total Some college, 1 or more years, no degree',
 "Total Associate's degree",
 "Total Bachelor's degree",
 "Total Master's degree",
 'Total Professional school degree',
 'Total Doctorate degree']

In [51]:
# remove quotes and the leading "Total " prefix from the detail columns
cleaned = []
for c in df_edu.columns:
    c = c.strip().replace('"', '').replace("'", "'")
    if c.startswith("Total ") and c != "Total":
        c = c.replace("Total ", "", 1)
    cleaned.append(c)

df_edu.columns = cleaned
df_edu.columns.tolist()

['GEO_ID',
 'NAME',
 'Total',
 'No schooling completed',
 'Nursery school',
 'Kindergarten',
 '1st grade',
 '2nd grade',
 '3rd grade',
 '4th grade',
 '5th grade',
 '6th grade',
 '7th grade',
 '8th grade',
 '9th grade',
 '10th grade',
 '11th grade',
 '12th grade, no diploma',
 'Regular high school diploma',
 'GED or alternative credential',
 'Some college, less than 1 year',
 'Some college, 1 or more years, no degree',
 "Associate's degree",
 "Bachelor's degree",
 "Master's degree",
 'Professional school degree',
 'Doctorate degree']

In [53]:
df_edu["<HS"] = df_edu[
    [
        "No schooling completed",
        "Nursery school",
        "Kindergarten",
        "1st grade", "2nd grade", "3rd grade", "4th grade",
        "5th grade", "6th grade", "7th grade", "8th grade",
        "9th grade", "10th grade", "11th grade",
        "12th grade, no diploma"
    ]
].sum(axis=1)

df_edu["HS_grad"] = df_edu[
    ["Regular high school diploma", "GED or alternative credential"]
].sum(axis=1)

df_edu["Some_college"] = df_edu[
    [
        "Some college, less than 1 year",
        "Some college, 1 or more years, no degree",
        "Associate's degree"
    ]
].sum(axis=1)

df_edu["College_grad"] = df_edu[
    ["Bachelor's degree", "Master's degree", "Professional school degree", "Doctorate degree"]
].sum(axis=1)

df_edu["Total_25_plus"] = df_edu["Total"]
df_edu["educ_sum"] = df_edu["<HS"] + df_edu["HS_grad"] + df_edu["Some_college"] + df_edu["College_grad"]

df_edu[["NAME", "Total_25_plus", "educ_sum"]].head()

                      NAME  Total_25_plus  educ_sum
0  Autauga County, Alabama          37860     37860
1  Baldwin County, Alabama         155563    155563
2  Barbour County, Alabama          17797     17797
3     Bibb County, Alabama          15987     15987
4   Blount County, Alabama          39814     39814

In [55]:
import pandas as pd
import re

df_inc = pd.read_csv(r"C:\Users\kband\Documents\ACS2020-2021\ACSDT5Y2020.B19001-Data.csv", skiprows=1)

# rename id columns
df_inc = df_inc.rename(columns={
    "Geography": "GEO_ID",
    "Geographic Area Name": "NAME"
})

# keep only estimate columns
estimate_cols = ["GEO_ID", "NAME"] + [c for c in df_inc.columns if str(c).startswith("Estimate!!")]
df_inc = df_inc[estimate_cols].copy()

def clean_income_col(c):
    c = str(c)

    # remove ACS prefixes
    c = c.replace("Estimate!!Total!!", "")
    c = c.replace("Estimate!!", "")
    c = c.replace("Total!!", "")
    c = c.replace("Total:", "")
    c = c.replace("Total ", "")

    # remove symbols and normalize formatting
    c = c.replace("$", "")
    c = c.replace(",", "")
    c = c.replace(" to ", "-")
    c = c.replace(" or more", "+")
    c = c.replace("Less than ", "<")
    c = c.replace(":", "")
    c = re.sub(r"\s+", " ", c).strip()

    return c

df_inc.columns = [clean_income_col(c) if c not in ["GEO_ID", "NAME"] else c for c in df_inc.columns]

print(df_inc.columns.tolist())

['GEO_ID', 'NAME', '', '!!<10000', '!!10000-14999', '!!15000-19999', '!!20000-24999', '!!25000-29999', '!!30000-34999', '!!35000-39999', '!!40000-44999', '!!45000-49999', '!!50000-59999', '!!60000-74999', '!!75000-99999', '!!100000-124999', '!!125000-149999', '!!150000-199999', '!!200000+']

In [57]:
import re

# rename the blank total column
df_inc = df_inc.rename(columns={'': 'Total'})

# strip leading !! from every column name
df_inc.columns = [re.sub(r'^!!+', '', str(c)).strip() for c in df_inc.columns]

df_inc.columns.tolist()

['GEO_ID',
 'NAME',
 'Total',
 '<10000',
 '10000-14999',
 '15000-19999',
 '20000-24999',
 '25000-29999',
 '30000-34999',
 '35000-39999',
 '40000-44999',
 '45000-49999',
 '50000-59999',
 '60000-74999',
 '75000-99999',
 '100000-124999',
 '125000-149999',
 '150000-199999',
 '200000+']

In [59]:
df_inc["Low"] = df_inc[
    ["<10000", "10000-14999", "15000-19999", "20000-24999", "25000-29999", "30000-34999"]
].sum(axis=1)

df_inc["Mid"] = df_inc[
    ["35000-39999", "40000-44999", "45000-49999", "50000-59999", "60000-74999", "75000-99999"]
].sum(axis=1)

df_inc["High"] = df_inc[
    ["100000-124999", "125000-149999", "150000-199999", "200000+"]
].sum(axis=1)

df_inc["Total_households"] = df_inc["Total"]
df_inc["income_sum"] = df_inc["Low"] + df_inc["Mid"] + df_inc["High"]

df_inc[["NAME", "Total_households", "income_sum"]].head()

                      NAME  Total_households  income_sum
0  Autauga County, Alabama             21559       21559
1  Baldwin County, Alabama             84047       84047
2  Barbour County, Alabama              9322        9322
3     Bibb County, Alabama              7259        7259
4   Blount County, Alabama             21205       21205

In [61]:
df_race 
# columns: GEO_ID, NAME, year, race, population

,GEO_ID,NAME,Total,NH_White,NH_Black,AIAN,Asian,NHOPI,Other,Multiracial,Hispanic,race_sum
0,0500000US01001,"Autauga County, Alabama",55639,41160,10849,155,649,0,101,1124,1601,55639
1,0500000US01003,"Baldwin County, Alabama",218289,180955,19027,1327,2033,10,740,4250,9947,218289
2,0500000US01005,"Barbour County, Alabama",25026,11332,11889,81,122,1,157,334,1110,25026
3,0500000US01007,"Bibb County, Alabama",22374,16650,4971,12,56,0,0,85,600,22374
4,0500000US01009,"Blount County, Alabama",57755,50065,771,49,236,55,179,1038,5362,57755
...,...,...,...,...,...,...,...,...,...,...,...,...
3216,0500000US72145,"Vega Baja Municipio, Puerto Rico",51089,1347,8,0,0,1,137,0,49596,51089
3217,0500000US72147,"Vieques Municipio, Puerto Rico",8508,520,28,0,0,0,0,0,7960,8508
3218,0500000US72149,"Villalba Municipio, Puerto Rico",21899,36,17,0,0,0,0,0,21846,21899
3219,0500000US72151,"Yabucoa Municipio, Puerto Rico",32867,22,0,0,0,0,0,0,32845,32867
3220,0500000US72153,"Yauco Municipio, Puerto Rico",34501,138,23,0,5,0,111,45,34179,34501

In [63]:
df_edu
# GEO_ID, NAME, <HS, HS_grad, Some_college, College_grad

,GEO_ID,NAME,Total,No schooling completed,Nursery school,Kindergarten,1st grade,2nd grade,3rd grade,4th grade,...,Bachelor's degree,Master's degree,Professional school degree,Doctorate degree,<HS,HS_grad,Some_college,College_grad,Total_25_plus,educ_sum
0,0500000US01001,"Autauga County, Alabama",37860,275,0,0,35,0,17,25,...,6320,3399,504,498,4273,11880,10986,10721,37860,37860
1,0500000US01003,"Baldwin County, Alabama",155563,1451,0,63,0,123,70,198,...,31444,13331,2845,2016,14823,42272,48832,49636,155563,155563
2,0500000US01005,"Barbour County, Alabama",17797,384,0,0,0,82,124,7,...,1296,540,118,113,4497,6361,4872,2067,17797,17797
3,0500000US01007,"Bibb County, Alabama",15987,323,0,18,0,0,13,0,...,1183,481,109,41,3056,7206,3911,1814,15987,15987
4,0500000US01009,"Blount County, Alabama",39814,805,14,0,5,19,50,343,...,3540,1382,222,132,6838,13975,13725,5276,39814,39814
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3216,0500000US72145,"Vega Baja Municipio, Puerto Rico",36640,892,0,0,90,244,501,687,...,5707,1776,182,283,9683,10459,8550,7948,36640,36640
3217,0500000US72147,"Vieques Municipio, Puerto Rico",5998,244,0,0,0,18,82,151,...,434,141,0,207,1755,2726,735,782,5998,5998
3218,0500000US72149,"Villalba Municipio, Puerto Rico",15044,310,0,0,18,173,212,307,...,2413,474,51,32,3240,5624,3210,2970,15044,15044
3219,0500000US72151,"Yabucoa Municipio, Puerto Rico",23732,479,0,0,130,126,335,593,...,3567,490,44,85,6678,6140,6728,4186,23732,23732
3220,0500000US72153,"Yauco Municipio, Puerto Rico",25263,589,54,0,126,251,385,347,...,4785,940,153,278,6126,8760,4221,6156,25263,25263

In [65]:
df_inc
# GEO_ID, NAME, Low, Mid, High

,GEO_ID,NAME,Total,<10000,10000-14999,15000-19999,20000-24999,25000-29999,30000-34999,35000-39999,...,75000-99999,100000-124999,125000-149999,150000-199999,200000+,Low,Mid,High,Total_households,income_sum
0,0500000US01001,"Autauga County, Alabama",21559,1331,982,1528,1134,1114,726,903,...,2893,2248,1288,1027,898,6815,9283,5461,21559,21559
1,0500000US01003,"Baldwin County, Alabama",84047,4352,4011,2930,3506,3935,4450,3789,...,11536,7621,5375,4893,5562,23184,37412,23451,84047,84047
2,0500000US01005,"Barbour County, Alabama",9322,1365,706,972,742,362,515,469,...,680,635,214,206,241,4662,3364,1296,9322,9322
3,0500000US01007,"Bibb County, Alabama",7259,799,512,382,382,377,283,217,...,1129,600,212,204,157,2735,3351,1173,7259,7259
4,0500000US01009,"Blount County, Alabama",21205,2145,968,885,1437,937,1445,961,...,2283,1540,1091,1034,580,7817,9143,4245,21205,21205
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3216,0500000US72145,"Vega Baja Municipio, Puerto Rico",19343,5000,2513,2106,1591,1300,1210,959,...,981,249,132,53,46,13720,5143,480,19343,19343
3217,0500000US72147,"Vieques Municipio, Puerto Rico",2405,710,640,212,137,150,218,83,...,11,22,12,0,0,2067,304,34,2405,2405
3218,0500000US72149,"Villalba Municipio, Puerto Rico",7932,1976,1187,922,565,747,393,434,...,170,179,9,91,17,5790,1846,296,7932,7932
3219,0500000US72151,"Yabucoa Municipio, Puerto Rico",11687,3468,1871,1345,705,1195,538,556,...,294,90,14,44,9,9122,2408,157,11687,11687
3220,0500000US72153,"Yauco Municipio, Puerto Rico",11654,4237,1649,1078,832,996,446,492,...,301,78,37,34,4,9238,2263,153,11654,11654

In [67]:
df_edu_long = df_edu.melt(
    id_vars=["GEO_ID", "NAME"],
    value_vars=["<HS", "HS_grad", "Some_college", "College_grad"],
    var_name="education",
    value_name="population"
)

In [69]:
df_inc_long = df_inc.melt(
    id_vars=["GEO_ID", "NAME"],
    value_vars=["Low", "Mid", "High"],
    var_name="income",
    value_name="population"
)

In [71]:
df_inc_long = df_inc.melt(
    id_vars=["GEO_ID", "NAME"],
    value_vars=["Low", "Mid", "High"],
    var_name="income",
    value_name="population"
)

In [73]:
df_race["prop"] = df_race["population"] / df_race.groupby(["GEO_ID", "year"])["population"].transform("sum")

KeyError: 'population'

In [75]:
df_race.columns.tolist()

['GEO_ID',
 'NAME',
 'Total',
 'NH_White',
 'NH_Black',
 'AIAN',
 'Asian',
 'NHOPI',
 'Other',
 'Multiracial',
 'Hispanic',
 'race_sum']

In [77]:
race_cols = ["NH_White", "NH_Black", "AIAN", "Asian", "NHOPI", "Other", "Multiracial", "Hispanic"]

df_race_long = df_race.melt(
    id_vars=["GEO_ID", "NAME", "year"],
    value_vars=race_cols,
    var_name="race",
    value_name="population"
)

KeyError: "The following id_vars or value_vars are not present in the DataFrame: ['year']"

In [79]:
df_race["year"] = 2020

In [81]:
race_cols = ["NH_White", "NH_Black", "AIAN", "Asian", "NHOPI", "Other", "Multiracial", "Hispanic"]

df_race_long = df_race.melt(
    id_vars=["GEO_ID", "NAME", "year"],
    value_vars=race_cols,
    var_name="race",
    value_name="population"
)

In [83]:
df_race_long = df_race.melt(
    id_vars=["GEO_ID", "NAME"],
    value_vars=race_cols,
    var_name="race",
    value_name="population"
)
df_race_long["year"] = 2020

In [85]:
df_race_long["prop"] = (
    df_race_long["population"] /
    df_race_long.groupby(["GEO_ID", "year"])["population"].transform("sum")
)

In [87]:
df_race["year"] = 2020

race_cols = ["NH_White", "NH_Black", "AIAN", "Asian", "NHOPI", "Other", "Multiracial", "Hispanic"]

df_race_long = df_race.melt(
    id_vars=["GEO_ID", "NAME", "year"],
    value_vars=race_cols,
    var_name="race",
    value_name="population"
)

df_race_long["prop"] = (
    df_race_long["population"] /
    df_race_long.groupby(["GEO_ID", "year"])["population"].transform("sum")
)

df_race_long.head()

,GEO_ID,NAME,year,race,population,prop
0,0500000US01001,"Autauga County, Alabama",2020,NH_White,41160,0.739769
1,0500000US01003,"Baldwin County, Alabama",2020,NH_White,180955,0.828970
2,0500000US01005,"Barbour County, Alabama",2020,NH_White,11332,0.452809
3,0500000US01007,"Bibb County, Alabama",2020,NH_White,16650,0.744167
4,0500000US01009,"Blount County, Alabama",2020,NH_White,50065,0.866851

In [89]:
df_race.columns.tolist()

['GEO_ID',
 'NAME',
 'Total',
 'NH_White',
 'NH_Black',
 'AIAN',
 'Asian',
 'NHOPI',
 'Other',
 'Multiracial',
 'Hispanic',
 'race_sum',
 'year']

In [91]:
race_cols = ["NH_White", "NH_Black", "AIAN", "Asian", "NHOPI", "Other", "Multiracial", "Hispanic"]

df_race_long = df_race.melt(
    id_vars=["GEO_ID", "NAME", "year"],
    value_vars=race_cols,
    var_name="race",
    value_name="population"
)

In [93]:
df_race_long.head()

           GEO_ID                     NAME  year      race  population
0  0500000US01001  Autauga County, Alabama  2020  NH_White       41160
1  0500000US01003  Baldwin County, Alabama  2020  NH_White      180955
2  0500000US01005  Barbour County, Alabama  2020  NH_White       11332
3  0500000US01007     Bibb County, Alabama  2020  NH_White       16650
4  0500000US01009   Blount County, Alabama  2020  NH_White       50065

In [95]:
df_race_long["prop"] = (
    df_race_long["population"] /
    df_race_long.groupby(["GEO_ID", "year"])["population"].transform("sum")
)

In [97]:
df_race_long.groupby(["GEO_ID","year"])["prop"].sum().head()

GEO_ID          year
0500000US01001  2020    1.0
0500000US01003  2020    1.0
0500000US01005  2020    1.0
0500000US01007  2020    1.0
0500000US01009  2020    1.0
Name: prop, dtype: float64

In [99]:
df_race_long.groupby(["GEO_ID","year"])["prop"].sum().head()

GEO_ID          year
0500000US01001  2020    1.0
0500000US01003  2020    1.0
0500000US01005  2020    1.0
0500000US01007  2020    1.0
0500000US01009  2020    1.0
Name: prop, dtype: float64

In [101]:
df_race_long.head()
df_edu_long.head()
df_inc_long.head()

           GEO_ID                     NAME income  population
0  0500000US01001  Autauga County, Alabama    Low        6815
1  0500000US01003  Baldwin County, Alabama    Low       23184
2  0500000US01005  Barbour County, Alabama    Low        4662
3  0500000US01007     Bibb County, Alabama    Low        2735
4  0500000US01009   Blount County, Alabama    Low        7817

In [103]:
display(df_race_long.head())
display(df_edu_long.head())
display(df_inc_long.head())

,GEO_ID,NAME,year,race,population,prop
0,0500000US01001,"Autauga County, Alabama",2020,NH_White,41160,0.739769
1,0500000US01003,"Baldwin County, Alabama",2020,NH_White,180955,0.828970
2,0500000US01005,"Barbour County, Alabama",2020,NH_White,11332,0.452809
3,0500000US01007,"Bibb County, Alabama",2020,NH_White,16650,0.744167
4,0500000US01009,"Blount County, Alabama",2020,NH_White,50065,0.866851

           GEO_ID                     NAME education  population
0  0500000US01001  Autauga County, Alabama       <HS        4273
1  0500000US01003  Baldwin County, Alabama       <HS       14823
2  0500000US01005  Barbour County, Alabama       <HS        4497
3  0500000US01007     Bibb County, Alabama       <HS        3056
4  0500000US01009   Blount County, Alabama       <HS        6838

           GEO_ID                     NAME income  population
0  0500000US01001  Autauga County, Alabama    Low        6815
1  0500000US01003  Baldwin County, Alabama    Low       23184
2  0500000US01005  Barbour County, Alabama    Low        4662
3  0500000US01007     Bibb County, Alabama    Low        2735
4  0500000US01009   Blount County, Alabama    Low        7817

In [105]:
df_edu_long["prop"] = (
    df_edu_long["population"] /
    df_edu_long.groupby("GEO_ID")["population"].transform("sum")
)

In [107]:
df_inc_long["prop"] = (
    df_inc_long["population"] /
    df_inc_long.groupby("GEO_ID")["population"].transform("sum")
)

In [109]:
df_edu_long.groupby("GEO_ID")["prop"].sum().head()
df_inc_long.groupby("GEO_ID")["prop"].sum().head()

GEO_ID
0500000US01001    1.0
0500000US01003    1.0
0500000US01005    1.0
0500000US01007    1.0
0500000US01009    1.0
Name: prop, dtype: float64

In [111]:
df_race_features = df_race_long.pivot_table(
    index=["GEO_ID", "year"],
    columns="race",
    values="prop"
).reset_index()

In [113]:
df_edu_features = df_edu_long.pivot_table(
    index="GEO_ID",
    columns="education",
    values="prop"
).reset_index()

In [115]:
df_inc_features = df_inc_long.pivot_table(
    index="GEO_ID",
    columns="income",
    values="prop"
).reset_index()

In [117]:
df_features = df_race_features.merge(df_edu_features, on="GEO_ID")
df_features = df_features.merge(df_inc_features, on="GEO_ID")

In [119]:
df_edu_long.head()

           GEO_ID                     NAME education  population      prop
0  0500000US01001  Autauga County, Alabama       <HS        4273  0.112863
1  0500000US01003  Baldwin County, Alabama       <HS       14823  0.095286
2  0500000US01005  Barbour County, Alabama       <HS        4497  0.252683
3  0500000US01007     Bibb County, Alabama       <HS        3056  0.191155
4  0500000US01009   Blount County, Alabama       <HS        6838  0.171749

In [121]:
df_inc_long.head()

           GEO_ID                     NAME income  population      prop
0  0500000US01001  Autauga County, Alabama    Low        6815  0.316109
1  0500000US01003  Baldwin County, Alabama    Low       23184  0.275846
2  0500000US01005  Barbour County, Alabama    Low        4662  0.500107
3  0500000US01007     Bibb County, Alabama    Low        2735  0.376774
4  0500000US01009   Blount County, Alabama    Low        7817  0.368639

In [123]:
df_features.head()

,GEO_ID,year,AIAN,Asian,Hispanic,Multiracial,NHOPI,NH_Black,NH_White,Other,<HS,College_grad,HS_grad,Some_college,High,Low,Mid
0,0500000US01001,2020,0.002786,0.011664,0.028775,0.020202,0.000000,0.194989,0.739769,0.001815,0.112863,0.283175,0.313788,0.290174,0.253305,0.316109,0.430586
1,0500000US01003,2020,0.006079,0.009313,0.045568,0.019470,0.000046,0.087164,0.828970,0.003390,0.095286,0.319073,0.271736,0.313905,0.279022,0.275846,0.445132
2,0500000US01005,2020,0.003237,0.004875,0.044354,0.013346,0.000040,0.475066,0.452809,0.006273,0.252683,0.116143,0.357420,0.273754,0.139026,0.500107,0.360867
3,0500000US01007,2020,0.000536,0.002503,0.026817,0.003799,0.000000,0.222178,0.744167,0.000000,0.191155,0.113467,0.450741,0.244636,0.161593,0.376774,0.461634
4,0500000US01009,2020,0.000848,0.004086,0.092840,0.017972,0.000952,0.013349,0.866851,0.003099,0.171749,0.132516,0.351007,0.344728,0.200189,0.368639,0.431172

In [125]:
df_race_long.groupby(["GEO_ID","year"])["prop"].sum().head()

GEO_ID          year
0500000US01001  2020    1.0
0500000US01003  2020    1.0
0500000US01005  2020    1.0
0500000US01007  2020    1.0
0500000US01009  2020    1.0
Name: prop, dtype: float64

In [127]:
df_edu_long.groupby("GEO_ID")["prop"].sum().head()

GEO_ID
0500000US01001    1.0
0500000US01003    1.0
0500000US01005    1.0
0500000US01007    1.0
0500000US01009    1.0
Name: prop, dtype: float64

In [129]:
df_inc_long.groupby("GEO_ID")["prop"].sum().head()

GEO_ID
0500000US01001    1.0
0500000US01003    1.0
0500000US01005    1.0
0500000US01007    1.0
0500000US01009    1.0
Name: prop, dtype: float64

In [131]:
df_edu_long["year"] = 2020
df_inc_long["year"] = 2020

In [133]:
df_race_long.to_csv("race_2020.csv", index=False)
df_edu_long.to_csv("edu_2020.csv", index=False)
df_inc_long.to_csv("inc_2020.csv", index=False)

In [134]:
import pandas as pd

def process_race(file_path, year):
    df = pd.read_csv(file_path, skiprows=1)

    # keep only what we need
    df = df.rename(columns={
        "Geography": "GEO_ID",
        "Geographic Area Name": "NAME"
    })

    def get_col(text):
        matches = [c for c in df.columns if text in c]
        if not matches:
            raise KeyError(f"Missing column containing: {text}")
        return matches[0]

    df["Total"] = pd.to_numeric(df[get_col("Estimate!!Total:")], errors="coerce")
    df["NH_White"] = pd.to_numeric(df[get_col("Not Hispanic or Latino:!!White alone")], errors="coerce")
    df["NH_Black"] = pd.to_numeric(df[get_col("Not Hispanic or Latino:!!Black or African American alone")], errors="coerce")
    df["AIAN"] = pd.to_numeric(df[get_col("Not Hispanic or Latino:!!American Indian and Alaska Native alone")], errors="coerce")
    df["Asian"] = pd.to_numeric(df[get_col("Not Hispanic or Latino:!!Asian alone")], errors="coerce")
    df["NHOPI"] = pd.to_numeric(df[get_col("Not Hispanic or Latino:!!Native Hawaiian and Other Pacific Islander alone")], errors="coerce")
    df["Other"] = pd.to_numeric(df[get_col("Not Hispanic or Latino:!!Some other race alone")], errors="coerce")
    df["Multiracial"] = pd.to_numeric(df[get_col("Not Hispanic or Latino:!!Two or more races")], errors="coerce")
    df["Hispanic"] = pd.to_numeric(df[get_col("Hispanic or Latino")], errors="coerce")

    race_cols = ["NH_White", "NH_Black", "AIAN", "Asian", "NHOPI", "Other", "Multiracial", "Hispanic"]

    df_long = df.melt(
        id_vars=["GEO_ID", "NAME"],
        value_vars=race_cols,
        var_name="race",
        value_name="population"
    )

    df_long["year"] = year
    df_long["prop"] = df_long["population"] / df_long.groupby("GEO_ID")["population"].transform("sum")

    return df_long

In [137]:
race_2021 = process_race(
    r"C:\Users\kband\Documents\ACS2020-2021\ACSDT5Y2021.B03002-Data.csv",
    2021
)

race_2021.head()

,GEO_ID,NAME,race,population,year,prop
0,0500000US01001,"Autauga County, Alabama",NH_White,42571,2021,0.376975
1,0500000US01003,"Baldwin County, Alabama",NH_White,187548,2021,0.433142
2,0500000US01005,"Barbour County, Alabama",NH_White,11268,2021,0.233941
3,0500000US01007,"Bibb County, Alabama",NH_White,16596,2021,0.381027
4,0500000US01009,"Blount County, Alabama",NH_White,50595,2021,0.474874

In [139]:
race_2022 = process_race(r"C:\Users\kband\Documents\ACS2020-2021\ACSDT5Y2022.B03002-Data.csv", 2022)
race_2023 = process_race(r"C:\Users\kband\Documents\ACS2020-2021\ACSDT5Y2023.B03002-Data.csv", 2023)
race_2024 = process_race(r"C:\Users\kband\Documents\ACS2020-2021\ACSDT1Y2024.B03002-Data.csv", 2024)

In [141]:
race_all = pd.concat([df_race_long, race_2021, race_2022, race_2023, race_2024], ignore_index=True)

In [143]:
race_all.groupby(["GEO_ID", "year"])["prop"].sum().head()

GEO_ID          year
0500000US01001  2020    1.0
                2021    1.0
                2022    1.0
                2023    1.0
0500000US01003  2020    1.0
Name: prop, dtype: float64

In [145]:
race_all.to_csv("race_all_2020_2024.csv", index=False)

In [146]:
race_all.groupby(["GEO_ID","year"])["prop"].sum().unique()
edu_all.groupby(["GEO_ID","year"])["prop"].sum().unique()
inc_all.groupby(["GEO_ID","year"])["prop"].sum().unique()

NameError: name 'edu_all' is not defined

In [148]:
import pandas as pd

def process_education(file_path, year):
    df = pd.read_csv(file_path, skiprows=1)

    df = df.rename(columns={
        "Geography": "GEO_ID",
        "Geographic Area Name": "NAME"
    })

    def get_col(text):
        matches = [c for c in df.columns if text in c]
        if not matches:
            raise KeyError(f"Missing: {text}")
        return matches[0]

    # Build bins
    df["<HS"] = df[[c for c in df.columns if any(x in c for x in [
        "No schooling", "Nursery", "Kindergarten",
        "1st grade","2nd grade","3rd grade","4th grade",
        "5th grade","6th grade","7th grade","8th grade",
        "9th grade","10th grade","11th grade",
        "12th grade, no diploma"
    ])]].apply(pd.to_numeric, errors="coerce").sum(axis=1)

    df["HS_grad"] = (
        pd.to_numeric(df[get_col("Regular high school diploma")], errors="coerce") +
        pd.to_numeric(df[get_col("GED or alternative credential")], errors="coerce")
    )

    df["Some_college"] = df[[c for c in df.columns if any(x in c for x in [
        "Some college, less than 1 year",
        "Some college, 1 or more years, no degree",
        "Associate"
    ])]].apply(pd.to_numeric, errors="coerce").sum(axis=1)

    df["College_grad"] = df[[c for c in df.columns if any(x in c for x in [
        "Bachelor",
        "Master",
        "Professional school",
        "Doctorate"
    ])]].apply(pd.to_numeric, errors="coerce").sum(axis=1)

    # long format
    df_long = df.melt(
        id_vars=["GEO_ID","NAME"],
        value_vars=["<HS","HS_grad","Some_college","College_grad"],
        var_name="education",
        value_name="population"
    )

    df_long["year"] = year
    df_long["prop"] = df_long["population"] / df_long.groupby("GEO_ID")["population"].transform("sum")

    return df_long

In [150]:
edu_2021 = process_education(r"C:\Users\kband\Documents\ACS2020-2021\ACSDT1Y2021.B15003-Data.csv", 2021)
edu_2022 = process_education(r"C:\Users\kband\Documents\ACS2020-2021\ACSDT1Y2022.B15003-Data.csv", 2022)
edu_2023 = process_education(r"C:\Users\kband\Documents\ACS2020-2021\ACSDT1Y2023.B15003-Data.csv", 2023)
edu_2024 = process_education(r"C:\Users\kband\Documents\ACS2020-2021\ACSDT1Y2024.B15003-Data.csv", 2024)

In [152]:
import pandas as pd
import re

def process_income(file_path, year):
    df = pd.read_csv(file_path, skiprows=1)

    df = df.rename(columns={
        "Geography": "GEO_ID",
        "Geographic Area Name": "NAME"
    })

    def norm(s):
        s = str(s).lower()
        s = re.sub(r"[^a-z0-9]+", "", s)
        return s

    def find_col(fragment):
        frag = norm(fragment)
        matches = [c for c in df.columns if frag in norm(c)]
        if not matches:
            raise KeyError(f"Missing column containing: {fragment}")
        return matches[0]

    total_col = find_col("estimate total")
    df["Total"] = pd.to_numeric(df[total_col], errors="coerce")

    low_frags = [
        "less than $10,000",
        "$10,000 to $14,999",
        "$15,000 to $19,999",
        "$20,000 to $24,999",
        "$25,000 to $29,999",
        "$30,000 to $34,999"
    ]

    mid_frags = [
        "$35,000 to $39,999",
        "$40,000 to $44,999",
        "$45,000 to $49,999",
        "$50,000 to $59,999",
        "$60,000 to $74,999",
        "$75,000 to $99,999"
    ]

    high_frags = [
        "$100,000 to $124,999",
        "$125,000 to $149,999",
        "$150,000 to $199,999",
        "$200,000 or more"
    ]

    df["Low"] = sum(
        pd.to_numeric(df[find_col(frag)], errors="coerce")
        for frag in low_frags
    )

    df["Mid"] = sum(
        pd.to_numeric(df[find_col(frag)], errors="coerce")
        for frag in mid_frags
    )

    df["High"] = sum(
        pd.to_numeric(df[find_col(frag)], errors="coerce")
        for frag in high_frags
    )

    df_long = df.melt(
        id_vars=["GEO_ID", "NAME"],
        value_vars=["Low", "Mid", "High"],
        var_name="income",
        value_name="population"
    )

    df_long["year"] = year
    df_long["prop"] = df_long["population"] / df_long.groupby("GEO_ID")["population"].transform("sum")

    return df_long

In [154]:
inc_2021 = process_income(r"C:\Users\kband\Documents\ACS2020-2021\ACSDT5Y2021.B19001-Data.csv", 2021)
inc_2022 = process_income(r"C:\Users\kband\Documents\ACS2020-2021\ACSDT5Y2022.B19001-Data.csv", 2022)
inc_2023 = process_income(r"C:\Users\kband\Documents\ACS2020-2021\ACSDT5Y2023.B19001-Data.csv", 2023)
inc_2024 = process_income(r"C:\Users\kband\Documents\ACS2020-2021\ACSDT5Y2024.B19001-Data.csv", 2024)

In [156]:
inc_2021.head()

           GEO_ID                     NAME income  population  year      prop
0  0500000US01001  Autauga County, Alabama    Low        6421  2021  0.293787
1  0500000US01003  Baldwin County, Alabama    Low       22269  2021  0.255408
2  0500000US01005  Barbour County, Alabama    Low        4412  2021  0.485475
3  0500000US01007     Bibb County, Alabama    Low        2629  2021  0.371170
4  0500000US01009   Blount County, Alabama    Low        7047  2021  0.330845

In [158]:
edu_all = pd.concat([df_edu_long, edu_2021, edu_2022, edu_2023, edu_2024])
inc_all = pd.concat([df_inc_long, inc_2021, inc_2022, inc_2023, inc_2024])

In [164]:
edu_all.head()

,GEO_ID,NAME,education,population,prop,year
0,0500000US01001,"Autauga County, Alabama",<HS,4273.0,0.112863,2020
1,0500000US01003,"Baldwin County, Alabama",<HS,14823.0,0.095286,2020
2,0500000US01005,"Barbour County, Alabama",<HS,4497.0,0.252683,2020
3,0500000US01007,"Bibb County, Alabama",<HS,3056.0,0.191155,2020
4,0500000US01009,"Blount County, Alabama",<HS,6838.0,0.171749,2020

In [166]:
inc_all.head()

           GEO_ID                     NAME income  population      prop  year
0  0500000US01001  Autauga County, Alabama    Low        6815  0.316109  2020
1  0500000US01003  Baldwin County, Alabama    Low       23184  0.275846  2020
2  0500000US01005  Barbour County, Alabama    Low        4662  0.500107  2020
3  0500000US01007     Bibb County, Alabama    Low        2735  0.376774  2020
4  0500000US01009   Blount County, Alabama    Low        7817  0.368639  2020

In [168]:
race_all.head()

,GEO_ID,NAME,year,race,population,prop
0,0500000US01001,"Autauga County, Alabama",2020,NH_White,41160.0,0.739769
1,0500000US01003,"Baldwin County, Alabama",2020,NH_White,180955.0,0.828970
2,0500000US01005,"Barbour County, Alabama",2020,NH_White,11332.0,0.452809
3,0500000US01007,"Bibb County, Alabama",2020,NH_White,16650.0,0.744167
4,0500000US01009,"Blount County, Alabama",2020,NH_White,50065.0,0.866851

In [170]:
race_all["year"].value_counts().sort_index()
edu_all["year"].value_counts().sort_index()
inc_all["year"].value_counts().sort_index()

year
2020    9663
2021    9663
2022    9666
2023    9666
2024    9666
Name: count, dtype: int64

In [172]:
race_all.groupby(["GEO_ID","year"])["prop"].sum().unique()
edu_all.groupby(["GEO_ID","year"])["prop"].sum().unique()
inc_all.groupby(["GEO_ID","year"])["prop"].sum().unique()

array([1., 1., 1.])

In [174]:
race_all.to_csv("race_all_2020_2024.csv", index=False)
edu_all.to_csv("edu_all_2020_2024.csv", index=False)
inc_all.to_csv("inc_all_2020_2024.csv", index=False)