In [101]:
import pandas as pd
import numpy as np

path = "C:/Users/apate/OneDrive/Documents/ASU Spring2026/FSE570 Capstone/Behavioral_Risk_Factor_Surveillance_System_(BRFSS)_Prevalence_Data_(2011_to_present)_20260223.csv"
df = pd.read_csv(path)
df.head()

,Year,Locationabbr,Locationdesc,Class,Topic,Question,Response,Break_Out,Break_Out_Category,Sample_Size,...,Data_Value_Footnote,DataSource,ClassId,TopicId,LocationID,BreakoutID,BreakOutCategoryID,QuestionID,ResponseID,GeoLocation
0,2024,AK,Alaska,Overweight and Obesity (BMI),BMI Categories,Weight classification by Body Mass Index (BMI)...,Underweight (BMI 12.0-18.4),Overall,Overall,82,...,NaN,BRFSS,CLASS14,TOPIC09,2,BO1,CAT1,_BMI5CAT,RESP042,"(64.84507995700051, -147.72205903599973)"
1,2024,AK,Alaska,Overweight and Obesity (BMI),BMI Categories,Weight classification by Body Mass Index (BMI)...,Normal Weight (BMI 18.5-24.9),Overall,Overall,"1,510",...,NaN,BRFSS,CLASS14,TOPIC09,2,BO1,CAT1,_BMI5CAT,RESP041,"(64.84507995700051, -147.72205903599973)"
2,2024,AK,Alaska,Overweight and Obesity (BMI),BMI Categories,Weight classification by Body Mass Index (BMI)...,Overweight (BMI 25.0-29.9),Overall,Overall,"1,795",...,NaN,BRFSS,CLASS14,TOPIC09,2,BO1,CAT1,_BMI5CAT,RESP040,"(64.84507995700051, -147.72205903599973)"
3,2024,AK,Alaska,Overweight and Obesity (BMI),BMI Categories,Weight classification by Body Mass Index (BMI)...,Obese (BMI 30.0 - 99.8),Overall,Overall,"1,687",...,NaN,BRFSS,CLASS14,TOPIC09,2,BO1,CAT1,_BMI5CAT,RESP039,"(64.84507995700051, -147.72205903599973)"
4,2024,AK,Alaska,Overweight and Obesity (BMI),BMI Categories,Weight classification by Body Mass Index (BMI)...,Underweight (BMI 12.0-18.4),Male,Sex,29,...,NaN,BRFSS,CLASS14,TOPIC09,2,SEX1,CAT2,_BMI5CAT,RESP042,"(64.84507995700051, -147.72205903599973)"

In [134]:
df['Question'].unique()

array(['Weight classification by Body Mass Index (BMI) (variable calculated from one or more BRFSS questions)'],
      dtype=object)

In [110]:
print(df.shape)
print(df.columns)
df.dtypes

(76370, 27)
Index(['Year', 'Locationabbr', 'Locationdesc', 'Class', 'Topic', 'Question',
       'Response', 'Break_Out', 'Break_Out_Category', 'Sample_Size',
       'Data_value', 'Confidence_limit_Low', 'Confidence_limit_High',
       'Display_order', 'Data_value_unit', 'Data_value_type',
       'Data_Value_Footnote_Symbol', 'Data_Value_Footnote', 'DataSource',
       'ClassId', 'TopicId', 'LocationID', 'BreakoutID', 'BreakOutCategoryID',
       'QuestionID', 'ResponseID', 'GeoLocation'],
      dtype='object')

Year                            int64
Locationabbr                   object
Locationdesc                   object
Class                          object
Topic                          object
Question                       object
Response                       object
Break_Out                      object
Break_Out_Category             object
Sample_Size                    object
Data_value                    float64
Confidence_limit_Low          float64
Confidence_limit_High         float64
Display_order                  object
Data_value_unit                object
Data_value_type                object
Data_Value_Footnote_Symbol     object
Data_Value_Footnote            object
DataSource                     object
ClassId                        object
TopicId                        object
LocationID                      int64
BreakoutID                     object
BreakOutCategoryID             object
QuestionID                     object
ResponseID                     object
GeoLocation                    object
dtype: object

In [116]:
# 2023 Alabama data
al_bmi = df[(df["Locationabbr"] == "AL") & (df["Year"] == 2023)].copy()

al_bmi["Conf_int"] = al_bmi["Confidence_limit_High"]- al_bmi["Data_value"]
al_bmi = al_bmi[["Year",'Locationabbr','Topic','Response','Break_Out','Break_Out_Category','Sample_Size','Data_value','Conf_int']].copy()

al_bmi

,Year,Locationabbr,Topic,Response,Break_Out,Break_Out_Category,Sample_Size,Data_value,Conf_int
6056,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),Overall,Overall,80,2.0,0.7
6057,2023,AL,BMI Categories,Normal Weight (BMI 18.5-24.9),Overall,Overall,"1,061",26.0,1.8
6058,2023,AL,BMI Categories,Overweight (BMI 25.0-29.9),Overall,Overall,"1,340",32.7,1.9
6059,2023,AL,BMI Categories,Obese (BMI 30.0 - 99.8),Overall,Overall,"1,596",39.2,2.0
6060,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),Male,Sex,28,2.2,1.0
...,...,...,...,...,...,...,...,...,...
6163,2023,AL,BMI Categories,Obese (BMI 30.0 - 99.8),"$100,000-$199,999",Household Income,253,38.8,4.7
6164,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),"$200,000+",Household Income,4,NaN,NaN
6165,2023,AL,BMI Categories,Normal Weight (BMI 18.5-24.9),"$200,000+",Household Income,60,27.8,7.5
6166,2023,AL,BMI Categories,Overweight (BMI 25.0-29.9),"$200,000+",Household Income,67,39.9,9.3
6167,2023,AL,BMI Categories,Obese (BMI 30.0 - 99.8),"$200,000+",Household Income,55,31.2,8.4

In [118]:
## 25 was largest sample size that left response as NAN
al_bmi[al_bmi.isna().any(axis=1)]

,Year,Locationabbr,Topic,Response,Break_Out,Break_Out_Category,Sample_Size,Data_value,Conf_int
6068,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),18-24,Age Group,10,NaN,NaN
6072,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),25-34,Age Group,4,NaN,NaN
6076,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),35-44,Age Group,4,NaN,NaN
6080,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),45-54,Age Group,9,NaN,NaN
6084,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),55-64,Age Group,7,NaN,NaN
6096,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),"Black, non-Hispanic",Race/Ethnicity,17,NaN,NaN
6100,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),"American Indian or Alaskan Native, non-Hispanic",Race/Ethnicity,0,NaN,NaN
6101,2023,AL,BMI Categories,Normal Weight (BMI 18.5-24.9),"American Indian or Alaskan Native, non-Hispanic",Race/Ethnicity,6,NaN,NaN
6102,2023,AL,BMI Categories,Overweight (BMI 25.0-29.9),"American Indian or Alaskan Native, non-Hispanic",Race/Ethnicity,11,NaN,NaN
6103,2023,AL,BMI Categories,Obese (BMI 30.0 - 99.8),"American Indian or Alaskan Native, non-Hispanic",Race/Ethnicity,15,NaN,NaN
6104,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),"Asian, non-Hispanic",Race/Ethnicity,3,NaN,NaN
6105,2023,AL,BMI Categories,Normal Weight (BMI 18.5-24.9),"Asian, non-Hispanic",Race/Ethnicity,25,NaN,NaN
6106,2023,AL,BMI Categories,Overweight (BMI 25.0-29.9),"Asian, non-Hispanic",Race/Ethnicity,7,NaN,NaN
6107,2023,AL,BMI Categories,Obese (BMI 30.0 - 99.8),"Asian, non-Hispanic",Race/Ethnicity,5,NaN,NaN
6108,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),"Native Hawaiian or other Pacific Islander, non...",Race/Ethnicity,1,NaN,NaN
6109,2023,AL,BMI Categories,Normal Weight (BMI 18.5-24.9),"Native Hawaiian or other Pacific Islander, non...",Race/Ethnicity,0,NaN,NaN
6110,2023,AL,BMI Categories,Overweight (BMI 25.0-29.9),"Native Hawaiian or other Pacific Islander, non...",Race/Ethnicity,1,NaN,NaN
6111,2023,AL,BMI Categories,Obese (BMI 30.0 - 99.8),"Native Hawaiian or other Pacific Islander, non...",Race/Ethnicity,3,NaN,NaN
6112,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),"Other, non-Hispanic",Race/Ethnicity,0,NaN,NaN
6113,2023,AL,BMI Categories,Normal Weight (BMI 18.5-24.9),"Other, non-Hispanic",Race/Ethnicity,1,NaN,NaN
6114,2023,AL,BMI Categories,Overweight (BMI 25.0-29.9),"Other, non-Hispanic",Race/Ethnicity,9,NaN,NaN
6115,2023,AL,BMI Categories,Obese (BMI 30.0 - 99.8),"Other, non-Hispanic",Race/Ethnicity,9,NaN,NaN
6116,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),"Multiracial, non-Hispanic",Race/Ethnicity,2,NaN,NaN
6120,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),Hispanic,Race/Ethnicity,0,NaN,NaN
6124,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),Less than H.S.,Education Attained,5,NaN,NaN
6140,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),"Less than $15,000",Household Income,7,NaN,NaN
6144,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),"$15,000-$24,999",Household Income,12,NaN,NaN
6148,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),"$25,000-$34,999",Household Income,12,NaN,NaN
6152,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),"$35,000-$49,999",Household Income,8,NaN,NaN
6156,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),"$50,000-$99,999",Household Income,5,NaN,NaN
6160,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),"$100,000-$199,999",Household Income,9,NaN,NaN
6164,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),"$200,000+",Household Income,4,NaN,NaN

In [120]:
# Split data by Obese (BMI > 30) and Not Obese (Bmi < 30)
bmi_under_30 = [
    "Underweight (BMI 12.0-18.4)",
    "Normal Weight (BMI 18.5-24.9)",
    "Overweight (BMI 25.0-29.9)"
]

al_bmi["Response_Mod"] = "BMI > 30"

al_bmi.loc[al_bmi["Response"].isin(bmi_under_30),"Response_Mod"] = "BMI < 30"
al_bmi.head(20)

,Year,Locationabbr,Topic,Response,Break_Out,Break_Out_Category,Sample_Size,Data_value,Conf_int,Response_Mod
6056,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),Overall,Overall,80,2.0,0.7,BMI < 30
6057,2023,AL,BMI Categories,Normal Weight (BMI 18.5-24.9),Overall,Overall,"1,061",26.0,1.8,BMI < 30
6058,2023,AL,BMI Categories,Overweight (BMI 25.0-29.9),Overall,Overall,"1,340",32.7,1.9,BMI < 30
6059,2023,AL,BMI Categories,Obese (BMI 30.0 - 99.8),Overall,Overall,"1,596",39.2,2.0,BMI > 30
6060,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),Male,Sex,28,2.2,1.0,BMI < 30
6061,2023,AL,BMI Categories,Normal Weight (BMI 18.5-24.9),Male,Sex,406,24.2,2.7,BMI < 30
6062,2023,AL,BMI Categories,Overweight (BMI 25.0-29.9),Male,Sex,644,35.8,2.9,BMI < 30
6063,2023,AL,BMI Categories,Obese (BMI 30.0 - 99.8),Male,Sex,642,37.8,2.9,BMI > 30
6064,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),Female,Sex,52,1.9,0.8,BMI < 30
6065,2023,AL,BMI Categories,Normal Weight (BMI 18.5-24.9),Female,Sex,655,27.7,2.5,BMI < 30
6066,2023,AL,BMI Categories,Overweight (BMI 25.0-29.9),Female,Sex,696,29.7,2.5,BMI < 30
6067,2023,AL,BMI Categories,Obese (BMI 30.0 - 99.8),Female,Sex,954,40.6,2.7,BMI > 30
6068,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),18-24,Age Group,10,NaN,NaN,BMI < 30
6069,2023,AL,BMI Categories,Normal Weight (BMI 18.5-24.9),18-24,Age Group,86,39.0,7.9,BMI < 30
6070,2023,AL,BMI Categories,Overweight (BMI 25.0-29.9),18-24,Age Group,59,29.7,7.2,BMI < 30
6071,2023,AL,BMI Categories,Obese (BMI 30.0 - 99.8),18-24,Age Group,53,26.1,7.0,BMI > 30
6072,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),25-34,Age Group,4,NaN,NaN,BMI < 30
6073,2023,AL,BMI Categories,Normal Weight (BMI 18.5-24.9),25-34,Age Group,121,28.7,5.0,BMI < 30
6074,2023,AL,BMI Categories,Overweight (BMI 25.0-29.9),25-34,Age Group,120,30.5,5.2,BMI < 30
6075,2023,AL,BMI Categories,Obese (BMI 30.0 - 99.8),25-34,Age Group,155,39.5,5.5,BMI > 30

In [128]:
# Calculate weighted mean of Obese and Not Obese by breakout in each breakout category
al_bmi["Data_value"] = pd.to_numeric(al_bmi["Data_value"])
al_bmi["Sample_Size"] = (
    al_bmi["Sample_Size"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .replace("nan", np.nan)
    .astype(float)
)

# Start with original values
al_bmi["Data_value_Mod"] = al_bmi["Data_value"]

# Mask for BMI < 30
m = al_bmi["Response_Mod"].eq("BMI < 30")

group_cols = ["Break_Out", "Break_Out_Category"]

# Compute weighted means excluding NaNs
wmean = (
    al_bmi.loc[m]
    .groupby(group_cols)[["Data_value", "Sample_Size"]]
    .apply(
        lambda g: np.average(
            g["Data_value"].dropna(),
            weights=g.loc[g["Data_value"].notna(), "Sample_Size"]
        )
        if g["Data_value"].notna().any()
        else np.nan
    )
)

# Assign back to BMI < 30 rows
al_bmi.loc[m, "Data_value_Mod"] = (
    al_bmi.loc[m]
    .set_index(group_cols)
    .index.map(wmean)
    .to_numpy()
)
al_bmi.head(20)

,Year,Locationabbr,Topic,Response,Break_Out,Break_Out_Category,Sample_Size,Data_value,Conf_int,Response_Mod,Data_value_Mod
6056,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),Overall,Overall,80.0,2.0,0.7,BMI < 30,28.844821
6057,2023,AL,BMI Categories,Normal Weight (BMI 18.5-24.9),Overall,Overall,1061.0,26.0,1.8,BMI < 30,28.844821
6058,2023,AL,BMI Categories,Overweight (BMI 25.0-29.9),Overall,Overall,1340.0,32.7,1.9,BMI < 30,28.844821
6059,2023,AL,BMI Categories,Obese (BMI 30.0 - 99.8),Overall,Overall,1596.0,39.2,2.0,BMI > 30,39.200000
6060,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),Male,Sex,28.0,2.2,1.0,BMI < 30,30.558442
6061,2023,AL,BMI Categories,Normal Weight (BMI 18.5-24.9),Male,Sex,406.0,24.2,2.7,BMI < 30,30.558442
6062,2023,AL,BMI Categories,Overweight (BMI 25.0-29.9),Male,Sex,644.0,35.8,2.9,BMI < 30,30.558442
6063,2023,AL,BMI Categories,Obese (BMI 30.0 - 99.8),Male,Sex,642.0,37.8,2.9,BMI > 30,37.800000
6064,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),Female,Sex,52.0,1.9,0.8,BMI < 30,27.735923
6065,2023,AL,BMI Categories,Normal Weight (BMI 18.5-24.9),Female,Sex,655.0,27.7,2.5,BMI < 30,27.735923
6066,2023,AL,BMI Categories,Overweight (BMI 25.0-29.9),Female,Sex,696.0,29.7,2.5,BMI < 30,27.735923
6067,2023,AL,BMI Categories,Obese (BMI 30.0 - 99.8),Female,Sex,954.0,40.6,2.7,BMI > 30,40.600000
6068,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),18-24,Age Group,10.0,NaN,NaN,BMI < 30,35.215862
6069,2023,AL,BMI Categories,Normal Weight (BMI 18.5-24.9),18-24,Age Group,86.0,39.0,7.9,BMI < 30,35.215862
6070,2023,AL,BMI Categories,Overweight (BMI 25.0-29.9),18-24,Age Group,59.0,29.7,7.2,BMI < 30,35.215862
6071,2023,AL,BMI Categories,Obese (BMI 30.0 - 99.8),18-24,Age Group,53.0,26.1,7.0,BMI > 30,26.100000
6072,2023,AL,BMI Categories,Underweight (BMI 12.0-18.4),25-34,Age Group,4.0,NaN,NaN,BMI < 30,29.596266
6073,2023,AL,BMI Categories,Normal Weight (BMI 18.5-24.9),25-34,Age Group,121.0,28.7,5.0,BMI < 30,29.596266
6074,2023,AL,BMI Categories,Overweight (BMI 25.0-29.9),25-34,Age Group,120.0,30.5,5.2,BMI < 30,29.596266
6075,2023,AL,BMI Categories,Obese (BMI 30.0 - 99.8),25-34,Age Group,155.0,39.5,5.5,BMI > 30,39.500000

In [130]:
# Drop Response Column

bmi_under_30 = [
    "Underweight (BMI 12.0-18.4)",
    "Normal Weight (BMI 18.5-24.9)"
]

al_bmi = al_bmi[~al_bmi["Response"].isin(bmi_under_30)].copy()

al_bmi = al_bmi.drop(columns=["Response"])
al_bmi

,Year,Locationabbr,Topic,Break_Out,Break_Out_Category,Sample_Size,Data_value,Conf_int,Response_Mod,Data_value_Mod
6058,2023,AL,BMI Categories,Overall,Overall,1340.0,32.7,1.9,BMI < 30,28.844821
6059,2023,AL,BMI Categories,Overall,Overall,1596.0,39.2,2.0,BMI > 30,39.200000
6062,2023,AL,BMI Categories,Male,Sex,644.0,35.8,2.9,BMI < 30,30.558442
6063,2023,AL,BMI Categories,Male,Sex,642.0,37.8,2.9,BMI > 30,37.800000
6066,2023,AL,BMI Categories,Female,Sex,696.0,29.7,2.5,BMI < 30,27.735923
6067,2023,AL,BMI Categories,Female,Sex,954.0,40.6,2.7,BMI > 30,40.600000
6070,2023,AL,BMI Categories,18-24,Age Group,59.0,29.7,7.2,BMI < 30,35.215862
6071,2023,AL,BMI Categories,18-24,Age Group,53.0,26.1,7.0,BMI > 30,26.100000
6074,2023,AL,BMI Categories,25-34,Age Group,120.0,30.5,5.2,BMI < 30,29.596266
6075,2023,AL,BMI Categories,25-34,Age Group,155.0,39.5,5.5,BMI > 30,39.500000
6078,2023,AL,BMI Categories,35-44,Age Group,159.0,33.1,4.9,BMI < 30,28.354753
6079,2023,AL,BMI Categories,35-44,Age Group,215.0,45.3,5.2,BMI > 30,45.300000
6082,2023,AL,BMI Categories,45-54,Age Group,190.0,32.7,4.9,BMI < 30,28.000637
6083,2023,AL,BMI Categories,45-54,Age Group,277.0,44.6,5.1,BMI > 30,44.600000
6086,2023,AL,BMI Categories,55-64,Age Group,223.0,31.8,4.1,BMI < 30,26.901847
6087,2023,AL,BMI Categories,55-64,Age Group,364.0,46.8,4.3,BMI > 30,46.800000
6090,2023,AL,BMI Categories,65+,Age Group,589.0,36.0,3.1,BMI < 30,31.194389
6091,2023,AL,BMI Categories,65+,Age Group,532.0,33.6,3.2,BMI > 30,33.600000
6094,2023,AL,BMI Categories,"White, non-Hispanic",Race/Ethnicity,929.0,33.9,2.3,BMI < 30,30.379944
6095,2023,AL,BMI Categories,"White, non-Hispanic",Race/Ethnicity,946.0,36.0,2.4,BMI > 30,36.000000
6098,2023,AL,BMI Categories,"Black, non-Hispanic",Race/Ethnicity,324.0,30.4,3.6,BMI < 30,25.696325
6099,2023,AL,BMI Categories,"Black, non-Hispanic",Race/Ethnicity,556.0,48.8,4.0,BMI > 30,48.800000
6102,2023,AL,BMI Categories,"American Indian or Alaskan Native, non-Hispanic",Race/Ethnicity,11.0,NaN,NaN,BMI < 30,NaN
6103,2023,AL,BMI Categories,"American Indian or Alaskan Native, non-Hispanic",Race/Ethnicity,15.0,NaN,NaN,BMI > 30,NaN
6106,2023,AL,BMI Categories,"Asian, non-Hispanic",Race/Ethnicity,7.0,NaN,NaN,BMI < 30,NaN
6107,2023,AL,BMI Categories,"Asian, non-Hispanic",Race/Ethnicity,5.0,NaN,NaN,BMI > 30,NaN
6110,2023,AL,BMI Categories,"Native Hawaiian or other Pacific Islander, non...",Race/Ethnicity,1.0,NaN,NaN,BMI < 30,NaN
6111,2023,AL,BMI Categories,"Native Hawaiian or other Pacific Islander, non...",Race/Ethnicity,3.0,NaN,NaN,BMI > 30,NaN
6114,2023,AL,BMI Categories,"Other, non-Hispanic",Race/Ethnicity,9.0,NaN,NaN,BMI < 30,NaN
6115,2023,AL,BMI Categories,"Other, non-Hispanic",Race/Ethnicity,9.0,NaN,NaN,BMI > 30,NaN
6118,2023,AL,BMI Categories,"Multiracial, non-Hispanic",Race/Ethnicity,32.0,39.8,14.7,BMI < 30,32.423529
6119,2023,AL,BMI Categories,"Multiracial, non-Hispanic",Race/Ethnicity,27.0,37.6,14.8,BMI > 30,37.600000
6122,2023,AL,BMI Categories,Hispanic,Race/Ethnicity,27.0,26.9,10.8,BMI < 30,31.736364
6123,2023,AL,BMI Categories,Hispanic,Race/Ethnicity,35.0,36.6,11.5,BMI > 30,36.600000
6126,2023,AL,BMI Categories,Less than H.S.,Education Attained,113.0,34.4,6.6,BMI < 30,30.627979
6127,2023,AL,BMI Categories,Less than H.S.,Education Attained,133.0,38.0,7.0,BMI > 30,38.000000
6130,2023,AL,BMI Categories,H.S. or G.E.D.,Education Attained,366.0,31.2,3.6,BMI < 30,28.022108
6131,2023,AL,BMI Categories,H.S. or G.E.D.,Education Attained,452.0,39.4,3.7,BMI > 30,39.400000
6134,2023,AL,BMI Categories,Some post-H.S.,Education Attained,375.0,32.9,3.5,BMI < 30,27.240265
6135,2023,AL,BMI Categories,Some post-H.S.,Education Attained,503.0,42.9,3.7,BMI > 30,42.900000
6138,2023,AL,BMI Categories,College graduate,Education Attained,486.0,33.7,3.0,BMI < 30,31.598152
6139,2023,AL,BMI Categories,College graduate,Education Attained,507.0,35.0,3.0,BMI > 30,35.000000
6142,2023,AL,BMI Categories,"Less than $15,000",Household Income,61.0,24.7,7.7,BMI < 30,25.196154
6143,2023,AL,BMI Categories,"Less than $15,000",Household Income,99.0,46.7,10.1,BMI > 30,46.700000
6146,2023,AL,BMI Categories,"$15,000-$24,999",Household Income,108.0,31.5,6.7,BMI < 30,29.185714
6147,2023,AL,BMI Categories,"$15,000-$24,999",Household Income,118.0,39.4,7.5,BMI > 30,39.400000
6150,2023,AL,BMI Categories,"$25,000-$34,999",Household Income,128.0,32.4,6.0,BMI < 30,28.462136
6151,2023,AL,BMI Categories,"$25,000-$34,999",Household Income,171.0,41.5,6.4,BMI > 30,41.500000
6154,2023,AL,BMI Categories,"$35,000-$49,999",Household Income,170.0,31.3,5.0,BMI < 30,28.353333
6155,2023,AL,BMI Categories,"$35,000-$49,999",Household Income,237.0,42.4,5.4,BMI > 30,42.400000
6158,2023,AL,BMI Categories,"$50,000-$99,999",Household Income,340.0,35.7,4.0,BMI < 30,30.765306
6159,2023,AL,BMI Categories,"$50,000-$99,999",Household Income,383.0,40.0,4.1,BMI > 30,40.000000
6162,2023,AL,BMI Categories,"$100,000-$199,999",Household Income,223.0,34.1,4.7,BMI < 30,30.546842
6163,2023,AL,BMI Categories,"$100,000-$199,999",Household Income,253.0,38.8,4.7,BMI > 30,38.800000
6166,2023,AL,BMI Categories,"$200,000+",Household Income,67.0,39.9,9.3,BMI < 30,34.183465
6167,2023,AL,BMI Categories,"$200,000+",Household Income,55.0,31.2,8.4,BMI > 30,31.200000